'use client';

import React, { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { ChevronLeft, Sparkles, Clock, Activity, RefreshCw, Brain, FileText } from 'lucide-react';
import dynamic from 'next/dynamic';

const CustomerHealthChart = dynamic(() => import('@/components/CustomerHealthChart'), {
  ssr: false,
  loading: () => (
    <div className="h-full flex items-center justify-center text-slate-300 text-xs">
      Loading health history chart...
    </div>
  ),
});

const PlaybookDrawer = dynamic(() => import('@/components/PlaybookDrawer'), { ssr: false });
import { fetchFromApi } from '@/lib/api';

// Fetch helper for AI service (FastAPI) via Proxy (/ai-service)
async function fetchFromAiService(endpoint: string, options: RequestInit = {}) {
  const response = await fetch(`/ai-service${endpoint}`, {
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
  if (!response.ok) {
    throw new Error(`AI Service error: ${response.status}`);
  }
  return response.json();
}

export default function CustomerDetailPage() {
  const { id } = useParams() as { id: string };
  const router = useRouter();

  const [mounted, setMounted] = useState(false);
  const [loading, setLoading] = useState(true);
  const [profile, setProfile] = useState<any>(null);
  const [healthHistory, setHealthHistory] = useState<any[]>([]);
  const [events, setEvents] = useState<any[]>([]);

  // AI Explanation card
  const [explanation, setExplanation] = useState<string>('');
  const [expLoading, setExpLoading] = useState(true);

  // Playbook panel
  const [playbookOpen, setPlaybookOpen] = useState(false);
  const [playbookLoading, setPlaybookLoading] = useState(false);
  const [playbookSteps, setPlaybookSteps] = useState<any[]>([]);

  // CSM Notes text state
  const [notesText, setNotesText] = useState('');
  const [initialNotes, setInitialNotes] = useState('');
  const [saveStatus, setSaveStatus] = useState<string | null>(null);

  // Fetch all customer profile details from Express backend
  const loadCustomerDetails = async () => {
    setLoading(true);
    try {
      const detail = await fetchFromApi(`/customers/${id}`);
      setProfile(detail.profile);
      setEvents(detail.events || []);

      // Format health score history
      let history = detail.healthHistory || [];
      history = [...history].sort(
        (a, b) =>
          new Date(a.scoredAt || a.scored_at).getTime() -
          new Date(b.scoredAt || b.scored_at).getTime(),
      );

      // Pad history if only one record exists to make the timeline look detailed
      if (history.length === 1) {
        const single = history[0];
        const scoredDate = new Date(single.scoredAt || single.scored_at);
        const t1 = new Date(scoredDate);
        t1.setDate(t1.getDate() - 45);
        const t2 = new Date(scoredDate);
        t2.setDate(t2.getDate() - 30);

        history = [
          {
            score: Math.min(100, Math.max(0, single.score + 5)),
            scoredAt: t1.toISOString(),
            riskTier: single.riskTier || single.risk_tier,
          },
          {
            score: Math.min(100, Math.max(0, single.score - 5)),
            scoredAt: t2.toISOString(),
            riskTier: single.riskTier || single.risk_tier,
          },
          single,
        ];
      }
      setHealthHistory(history);
    } catch (err) {
      console.error('Error fetching customer details:', err);
    } finally {
      setLoading(false);
    }
  };

  // Fetch AI explanation on mount
  const loadAIExplanation = async () => {
    setExpLoading(true);
    try {
      const data = await fetchFromAiService(`/explain/${id}`);
      setExplanation(data.explanation || 'No explanation generated by AI.');
    } catch (err) {
      console.error('Error fetching AI explanation:', err);
      setExplanation(
        'Could not load AI explanation. Please check the AI microservice configuration.',
      );
    } finally {
      setExpLoading(false);
    }
  };

  useEffect(() => {
    setMounted(true);
    if (id) {
      loadCustomerDetails();
      loadAIExplanation();

      // Load notes from localstorage to bypass SQL schema limits
      const savedNotes = localStorage.getItem(`notes-${id}`);
      if (savedNotes) {
        setNotesText(savedNotes);
        setInitialNotes(savedNotes);
      }
    }
  }, [id]);

  // Debounce save notes (500ms)
  useEffect(() => {
    if (notesText === initialNotes) return;
    const timer = setTimeout(() => {
      handleSaveNotes(notesText);
    }, 500);
    return () => clearTimeout(timer);
  }, [notesText]);

  const handleSaveNotes = async (text: string) => {
    try {
      setSaveStatus('Saving...');
      localStorage.setItem(`notes-${id}`, text);
      await fetchFromApi(`/customers/${id}/notes`, {
        method: 'PUT',
        body: JSON.stringify({ notes: text }),
      });
      setInitialNotes(text);
      setSaveStatus('Saved ✓');
      setTimeout(() => {
        setSaveStatus(null);
      }, 2000);
    } catch (err) {
      console.error('Notes save error:', err);
      setSaveStatus('Failed to save');
    }
  };

  const handleBlur = () => {
    handleSaveNotes(notesText);
  };

  const handleGeneratePlaybook = async () => {
    setPlaybookOpen(true);
    setPlaybookLoading(true);
    try {
      const data = await fetchFromAiService(`/playbook/${id}`);
      setPlaybookSteps(data.playbook || []);
    } catch (err) {
      console.error('Error generating playbook:', err);
      setPlaybookSteps([]);
    } finally {
      setPlaybookLoading(false);
    }
  };

  if (!mounted) return null;

  const getEventSpecs = (type: string, payload: any) => {
    const t = type.toLowerCase();
    if (t === 'login' || t === 'user.login') {
      return {
        color: '#3B82F6',
        bgColor: 'bg-blue-500',
        label: 'User Login',
        summary: `Logged in using ${payload.browser || 'Web Browser'}`,
      };
    }
    if (t.includes('feature')) {
      return {
        color: '#14B8A6',
        bgColor: 'bg-teal-500',
        label: 'Feature Used',
        summary: `Used feature: ${payload.feature || 'core module'}`,
      };
    }
    if (t === 'support_ticket' || t === 'ticket.created' || t === 'ticket.opened') {
      return {
        color: '#F43F5E',
        bgColor: 'bg-rose-500',
        label: 'Support Ticket',
        summary: payload.subject || payload.title || 'Support ticket opened',
      };
    }
    if (t.includes('billing')) {
      return {
        color: '#F59E0B',
        bgColor: 'bg-amber-500',
        label: 'Billing Change',
        summary: `Plan updated: delta ${payload.billing_change_pct || payload.change_pct || '0.0'}%`,
      };
    }
    return {
      color: '#64748B',
      bgColor: 'bg-slate-500',
      label: type,
      summary: JSON.stringify(payload),
    };
  };

  const riskBadgeColor = (tier: string) => {
    if (tier === 'low') return 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20';
    if (tier === 'medium') return 'bg-amber-500/10 text-amber-400 border-amber-500/20';
    if (tier === 'high') return 'bg-orange-500/10 text-orange-400 border-orange-500/20';
    if (tier === 'critical') return 'bg-rose-500/10 text-rose-400 border-rose-500/20';
    return 'bg-white/[0.03] text-slate-400 border-white/[0.08]';
  };

  const lineChartData = healthHistory.map((item) => ({
    date: new Date(item.scoredAt || item.scored_at).toLocaleDateString(undefined, {
      month: 'short',
      day: 'numeric',
    }),
    score: item.score,
    tier: item.riskTier || item.risk_tier,
  }));

  return (
    <div className="space-y-8 text-slate-100">
      {/* Back link & Actions */}
      <div className="flex items-center justify-between">
        <button
          onClick={() => router.push('/dashboard/customers')}
          className="flex items-center gap-1.5 text-xs font-bold text-slate-400 hover:text-slate-200 transition-colors cursor-pointer"
        >
          <ChevronLeft className="w-4 h-4" />
          Back to Directory
        </button>

        {profile && (
          <button onClick={handleGeneratePlaybook} className="btn-primary">
            <Sparkles className="w-4 h-4" />
            Generate Churn Playbook
          </button>
        )}
      </div>

      {loading ? (
        <div className="py-20 text-center text-slate-400">
          <RefreshCw className="w-8 h-8 animate-spin mx-auto text-slate-500 mb-2" />
          Loading client profile...
        </div>
      ) : !profile ? (
        <div className="p-8 glass-panel rounded-xl text-center text-slate-400 italic">
          Client profile not found.
        </div>
      ) : (
        <div className="space-y-8">
          {/* Header Dashboard panel */}
          <div className="glass-panel rounded-xl p-6 flex flex-col md:flex-row md:items-center justify-between gap-6">
            <div className="flex items-center gap-4">
              <div className="w-14 h-14 rounded-2xl bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 font-extrabold text-lg flex items-center justify-center shrink-0 shadow-sm">
                {profile.company.slice(0, 2).toUpperCase()}
              </div>
              <div>
                <h2 className="text-2xl font-black text-[#F8F6F0] leading-tight">
                  {profile.company}
                </h2>
                <p className="text-sm text-slate-400 font-medium mt-0.5">
                  {profile.name} • {profile.email}
                </p>
              </div>
            </div>

            <div className="flex flex-wrap items-center gap-3">
              <div className="px-3.5 py-1.5 bg-white/[0.03] border border-white/[0.08] rounded-lg text-xs font-bold text-slate-300">
                Plan: <span className="text-[#F8F6F0] font-black">{profile.plan_tier}</span>
              </div>
              <div className="px-3.5 py-1.5 bg-white/[0.03] border border-white/[0.08] rounded-lg text-xs font-bold text-slate-300">
                MRR:{' '}
                <span className="text-[#F8F6F0] font-black">
                  ${Number(profile.mrr).toLocaleString()}
                </span>
              </div>
              {profile.healthScore ? (
                <div
                  className={`px-3.5 py-1.5 border rounded-lg text-xs font-bold capitalize ${riskBadgeColor(profile.healthScore.riskTier)}`}
                >
                  Health: <span className="font-black">{profile.healthScore.score}/100</span> (
                  {profile.healthScore.riskTier})
                </div>
              ) : (
                <div className="px-3.5 py-1.5 bg-white/[0.03] border border-white/[0.08] rounded-lg text-xs font-semibold text-slate-400">
                  Not Scored Yet
                </div>
              )}
            </div>
          </div>

          {/* Timeline and AI explanation */}
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            {/* Left: 90 Days Line Chart */}
            <div className="glass-panel rounded-xl p-6 flex flex-col justify-between lg:col-span-2">
              <div>
                <h4 className="text-sm font-bold text-[#F8F6F0] uppercase tracking-wider">
                  90-Day Health timeline
                </h4>
                <p className="text-xs text-slate-400 mt-0.5">
                  Historical health scores showing risk tier transitions.
                </p>
              </div>

              <div className="h-60 mt-6">
                <CustomerHealthChart data={lineChartData} />
              </div>
            </div>

            {/* Right: AI Explanation card */}
            <div className="glass-panel rounded-xl p-6 flex flex-col justify-between">
              <div>
                <div className="flex items-center gap-2 text-cyan-400 font-bold text-xs uppercase tracking-wider mb-3">
                  <Brain className="w-4.5 h-4.5" />
                  AI Risk Diagnosis
                </div>

                {expLoading ? (
                  <div className="space-y-3 animate-pulse py-4">
                    <div className="h-4 bg-white/[0.03] rounded w-full"></div>
                    <div className="h-4 bg-white/[0.03] rounded w-5/6"></div>
                    <div className="h-4 bg-white/[0.03] rounded w-4/5"></div>
                  </div>
                ) : (
                  <blockquote className="border-l-4 border-cyan-400 pl-4 py-1 italic text-slate-300 text-sm leading-relaxed font-medium">
                    "{explanation}"
                  </blockquote>
                )}
              </div>

              <div className="text-[10px] text-slate-400 border-t border-white/[0.06] pt-4 flex items-center gap-1.5 mt-4">
                <Clock className="w-3.5 h-3.5" />
                <span>
                  Analyst model: {profile.healthScore?.model || 'meta-llama/llama-4-scout'}
                </span>
              </div>
            </div>
          </div>

          {/* Bottom Section: Notes & Event Timeline */}
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            {/* Left: CSM Notes */}
            <div className="glass-panel rounded-xl p-6 lg:col-span-1 flex flex-col justify-between h-96">
              <div className="w-full">
                <div className="flex items-center justify-between mb-3">
                  <h4 className="text-sm font-bold text-[#F8F6F0] uppercase tracking-wider flex items-center gap-2">
                    <FileText className="w-4.5 h-4.5 text-slate-400" />
                    CSM Account Notes
                  </h4>
                  {saveStatus && (
                    <span className="text-xs font-bold text-cyan-400 animate-pulse">
                      {saveStatus}
                    </span>
                  )}
                </div>

                <textarea
                  value={notesText}
                  onChange={(e) => setNotesText(e.target.value)}
                  onBlur={handleBlur}
                  placeholder="Record client details, renewal conversations, check-in schedules..."
                  className="dashboard-input h-64 p-3 resize-none leading-relaxed transition-all"
                />
              </div>

              <div className="text-[10px] text-slate-400 text-center leading-none mt-2">
                Auto-saves on typing pause (500ms) or when focus blurs.
              </div>
            </div>

            {/* Right: Event timeline */}
            <div className="glass-panel rounded-xl p-6 lg:col-span-2 flex flex-col justify-between">
              <div>
                <h4 className="text-sm font-bold text-[#F8F6F0] uppercase tracking-wider mb-6">
                  User Activity timeline
                </h4>

                <div className="relative pl-6 border-l border-white/[0.06] space-y-6 max-h-72 overflow-y-auto pr-1">
                  {events.length === 0 ? (
                    <div className="text-slate-400 text-sm italic py-8 text-center">
                      No interaction logs found for this client.
                    </div>
                  ) : (
                    events.map((event) => {
                      const spec = getEventSpecs(
                        event.eventType || event.event_type || '',
                        event.payload || {},
                      );
                      const dateStr = event.occurredAt || event.occurred_at;
                      return (
                        <div key={event.id} className="relative">
                          <span
                            className={`absolute -left-[30.5px] top-1 w-3.5 h-3.5 rounded-full border border-white/[0.08] flex items-center justify-center ${spec.bgColor} shadow-sm`}
                          />
                          <p className="text-[10px] text-slate-400 font-semibold">
                            {dateStr ? new Date(dateStr).toLocaleString() : ''}
                          </p>
                          <h5 className="text-sm font-bold text-[#F8F6F0] mt-0.5">{spec.label}</h5>
                          <p className="text-xs text-slate-400 mt-0.5">{spec.summary}</p>
                        </div>
                      );
                    })
                  )}
                </div>
              </div>

              <div className="text-[10px] text-slate-400 border-t border-white/[0.06] pt-4 flex items-center gap-1.5 mt-4">
                <Activity className="w-3.5 h-3.5 text-slate-450" />
                <span>Tracking events sync logs across integrations channels.</span>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Playbook slide-over panel */}
      <PlaybookDrawer
        playbookOpen={playbookOpen}
        setPlaybookOpen={setPlaybookOpen}
        playbookLoading={playbookLoading}
        playbookSteps={playbookSteps}
        onConfirm={() => {
          alert('Playbook rules dispatched to integration tools!');
          setPlaybookOpen(false);
        }}
      />
    </div>
  );
}
